version: "2.3"

services:
    small_http_server-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/small_http_server/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/small_http_server:rw
        ports:
          - 8080:8080
        working_dir: /small_http_server
        entrypoint:
          - ./tests/run_as_user.sh
